---
title: "script"
author: "Jennifer Liu"
date: "2022-11-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(forecast)
```

```{r}
# read data
CO2 <- read.csv("CO2_Cleaned_V2.csv",sep = ",",na = c("","NA"))
CO2 %>% summarise_all(~sum(is.na(.)))
CO2<- CO2 %>% select(-c(8,9))

CO2_forecasting<-CO2 %>% 
  select(Country, Year, CO2.emission..Tons.)
# make sure no na
dim(CO2_forecasting)
dim(na.omit(CO2_forecasting))
# which years for forecasting
CO2_no_year_min[which(CO2_no_year_min$Year==max(CO2_no_year_min[]$Year)),]
# Use 1992-2019 data to forecast
CO2_forecasting<-CO2_forecasting %>% 
  filter(Year>1900&Year<2020) %>% 
  group_by(Country)
View(CO2_forecasting)

# forecast on top 6
# US
CO2_US<-CO2_forecasting %>%
  filter(Country=="United States")
# United Kingdom
CO2_UK<-CO2_forecasting %>%
  filter(Country=="United Kingdom")
# Germany
CO2_GE<-CO2_forecasting %>%
  filter(Country=="Germany")
# China
CO2_CH<-CO2_forecasting %>%
  filter(Country=="China")
# Russia
CO2_RU<-CO2_forecasting %>%
  filter(Country=="Russia")
# France
CO2_FR<-CO2_forecasting %>%
  filter(Country=="France")
# # India
# CO2_IN<-CO2_forecasting %>%
#   filter(Country=="India")

# # plot
# plot(CO2_US$Year, CO2_US$CO2.emission..Tons.)
# plot(CO2_UK$Year, CO2_UK$CO2.emission..Tons.)
# plot(CO2_GE$Year, CO2_GE$CO2.emission..Tons.)
# plot(CO2_CH$Year, CO2_CH$CO2.emission..Tons.)
# plot(CO2_RU$Year, CO2_RU$CO2.emission..Tons.)
# plot(CO2_FR$Year, CO2_FR$CO2.emission..Tons.)


# US
pred.us<-ts(CO2_US$CO2.emission..Tons., start=1992,frequency = 1) %>% 
  auto.arima() %>% 
  forecast(h=30)

# UK
pred.uk<-ts(CO2_UK$CO2.emission..Tons.,start=1992,frequency = 1) %>% 
  auto.arima() %>% 
  forecast(h=30)

# GE
pred.ge<-ts(CO2_GE$CO2.emission..Tons.,start=1992,frequency = 1) %>% 
  auto.arima() %>% 
  forecast(h=30)

# CH
pred.ch<-ts(CO2_CH$CO2.emission..Tons.,start=1992,frequency = 1) %>% 
  auto.arima() %>% 
  forecast(h=30)

# Russia
pred.ru<-ts(CO2_RU$CO2.emission..Tons.,start=1992,frequency = 1) %>% 
  auto.arima() %>% 
  forecast(h=30)

# FR
pred.fr<-ts(CO2_FR$CO2.emission..Tons.,start=1992,frequency = 1) %>% 
  auto.arima() %>% 
  forecast(h=30)

pred.in<-ts(CO2_IN$CO2.emission..Tons.,start=1992,frequency = 1) %>% 
  auto.arima() %>% 
  forecast(h=30)

# # plot
# par(mfrow=c(2,3))
# plot(pred.us)
# plot(pred.uk)
# plot(pred.ge)
# plot(pred.ch)
# plot(pred.ru)
# plot(pred.fr)

```

```{r}
library(devtools)
devtools::install_github('cttobin/ggthemr')
library(ggthemr)
ggthemr("dust")

US.plot<-autoplot(pred.us)+
  ggtitle("United States")+
  labs(x = "Year", y = "CO2 Emission")+
  theme(axis.title.x = element_text(vjust = 0),
        axis.title.y = element_text(vjust = 2))+
  ylim(c(2.75e+10, 6.5e+11))

UK.plot<-autoplot(pred.uk)+
  ggtitle("United Kingdom")+
  labs(x = "Year", y = "CO2 Emission")+
  theme(axis.title.x = element_text(vjust = 0),
        axis.title.y = element_text(vjust = 2))+
  ylim(c(2.75e+10, 6.5e+11))

GE.plot<-autoplot(pred.ge)+
  ggtitle("Germany")+
  labs(x = "Year", y = "CO2 Emission")+
  theme(axis.title.x = element_text(vjust = 0),
        axis.title.y = element_text(vjust = 2))+
  ylim(c(2.75e+10, 6.5e+11))

CH.plot<-autoplot(pred.ch)+
  ggtitle("China")+
  labs(x = "Year", y = "CO2 Emission")+
  theme(axis.title.x = element_text(vjust = 0),
        axis.title.y = element_text(vjust = 2))+
  ylim(c(2.75e+10, 6.5e+11))

RU.plot<-autoplot(pred.ru)+
  ggtitle("Russia")+
  labs(x = "Year", y = "CO2 Emission")+
  theme(axis.title.x = element_text(vjust = 0),
        axis.title.y = element_text(vjust = 2))+
  ylim(c(2.75e+10, 6.5e+11))

FR.plot<-autoplot(pred.fr)+
  ggtitle("France")+
  labs(x = "Year", y = "CO2 Emission")+
  theme(axis.title.x = element_text(vjust = 0),
        axis.title.y = element_text(vjust = 2))+
  ylim(c(2.75e+10, 6.5e+11))

US.plot
UK.plot
GE.plot
CH.plot
RU.plot
FR.plot

ggsave(
  "US.scaled.png",
  US.plot,
  width = 10,
  height = 7.5
)
ggsave(
  "UK.scaled.png",
  UK.plot,
  width = 10,
  height = 7.5
)
ggsave(
  "GE.scaled.png",
  GE.plot,
  width = 10,
  height = 7.5
)
ggsave(
  "CH.scaled.png",
  CH.plot,
  width = 10,
  height = 7.5
)
ggsave(
  "RU.scaled.png",
  RU.plot,
  width = 10,
  height = 7.5
)
ggsave(
  "FR.scaled.png",
  FR.plot,
  width = 10,
  height = 7.5
)
```


Continent
```{r}
# Continent
CO2 <- read.csv("CO2_Cleaned_V2.csv")
CO2$Continent <- countrycode(sourcevar = CO2[,"Country"],
                                  origin = "country.name",
                                  destination = "continent")
CO2_forecasting<-CO2 %>% 
  select(Country, Year, CO2.emission..Tons.,Continent)
# make sure no na
dim(CO2_forecasting)
dim(na.omit(CO2_forecasting))
# Use 1992-2020 data to forecast
CO2_no_year_min[which(CO2_no_year_min$Year==max(CO2_no_year_min[]$Year)),]
CO2_forecasting<-CO2_forecasting %>% 
  filter(Year>1991) %>% 
  group_by(Country)

# continent
CO2_forecasting_continent<-CO2_forecasting %>% 
  dplyr::group_by(Year, Continent) %>%
  dplyr::summarise(Sum=sum(CO2.emission..Tons.))
CO2_forecasting_continent<-na.omit(CO2_forecasting_continent)
# View(CO2_forecasting_continent)

Asia<-CO2_forecasting_continent %>% 
  filter(Continent=="Asia")

Europe<-CO2_forecasting_continent %>% 
  filter(Continent=="Europe")

Africa<-CO2_forecasting_continent %>% 
  filter(Continent=="Africa")

Americas<-CO2_forecasting_continent %>% 
  filter(Continent=="Americas")

Oceania<-CO2_forecasting_continent %>% 
  filter(Continent=="Oceania")

# forecasting
# Asia
ts_data_as = ts(Asia$Sum,start=1992,frequency = 1)
arima.ts.as = auto.arima(ts_data_as)
pred.as = forecast(arima.ts.as,h=30)

# EU
ts_data_eu = ts(Europe$Sum,start=1992,frequency = 1)
arima.ts.eu = auto.arima(ts_data_eu)
pred.eu = forecast(arima.ts.eu,h=30)

# AF
ts_data_af = ts(Africa$Sum,start=1992,frequency = 1)
arima.ts.af = auto.arima(ts_data_af)
pred.af = forecast(arima.ts.af,h=30)

# AM
ts_data_am = ts(Americas$Sum,start=1992,frequency = 1)
arima.ts.am = auto.arima(ts_data_am)
pred.am = forecast(arima.ts.am,h=30)

# OC
ts_data_oc = ts(Oceania$Sum,start=1992,frequency = 1)
arima.ts.oc = auto.arima(ts_data_oc)
pred.oc = forecast(arima.ts.oc,h=30)

# # plot
# par(mfrow=c(2,3)) 
# plot(pred.as, xaxt="n")
# plot(pred.eu, xaxt="n")
# plot(pred.af, xaxt="n")
# plot(pred.am, xaxt="n")
# plot(pred.oc, xaxt="n")
```

```{r}
Asia.plot<-autoplot(pred.as)+
  ggtitle("Asia")+
  labs(x = "Year", y = "CO2 Emission")+
  theme(axis.title.x = element_text(vjust = 0),
        axis.title.y = element_text(vjust = 2))+
  ylim(c(1e+10,2e+12))

Europe.plot<-autoplot(pred.eu)+
  ggtitle("Europe")+
  labs(x = "Year", y = "CO2 Emission")+
  theme(axis.title.x = element_text(vjust = 0),
        axis.title.y = element_text(vjust = 2))+
  ylim(c(1e+10,2e+12))

Africa.plot<-autoplot(pred.af)+
  ggtitle("Africa")+
  labs(x = "Year", y = "CO2 Emission")+
  theme(axis.title.x = element_text(vjust = 0),
        axis.title.y = element_text(vjust = 2))+
  ylim(c(1e+10,2e+12))

Americas.plot<-autoplot(pred.am)+
  ggtitle("Americas")+
  labs(x = "Year", y = "CO2 Emission")+
  theme(axis.title.x = element_text(vjust = 0),
        axis.title.y = element_text(vjust = 2))+
  ylim(c(1e+10,2e+12))

OC.plot<-autoplot(pred.oc)+
  ggtitle("Oceania")+
  labs(x = "Year", y = "CO2 Emission")+
  theme(axis.title.x = element_text(vjust = 0),
        axis.title.y = element_text(vjust = 2))+
  ylim(c(1e+10,2e+12))


ggsave(
  "Oceania.scaled.png",
  OC.plot,
  width = 10,
  height = 7.5
)

ggsave(
  "Asia.scaled.png",
  Asia.plot,
  width = 10,
  height = 7.5
)
ggsave(
  "Europe.scaled.png",
  Europe.plot,
  width = 10,
  height = 7.5
)
ggsave(
  "Africa.scaled.png",
  Africa.plot,
  width = 10,
  height = 7.5
)
ggsave(
  "Americas.scaled.png",
  Americas.plot,
  width = 10,
  height = 7.5
)

Asia.plot
Europe.plot
Americas.plot
OC.plot
Africa.plot
```

